version: '3.8'

services:
  credit-app:
    build: .
    container_name: credit-system
    networks:
      - credit-network
    volumes:
      - ./data:/app/data
      - /root/.open-webui:/open-webui:ro
    environment:
      - OPENWEBUI_DATABASE_PATH=/open-webui/webui.db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: credit-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - credit-app
    networks:
      - credit-network
    restart: unless-stopped

networks:
  credit-network:
    driver: bridge
