#!/bin/bash

echo "🔐 Security Configuration Summary"
echo "================================"
echo ""
echo "Admin Interface:"
echo "  URL: https://localhost:8000 (or http://localhost:8000)"
echo "  Username: \$ADMIN_USERNAME (default: admin)"
echo "  Password: \$ADMIN_PASSWORD (default: admin123)"
echo ""
echo "Extension API Key:"
echo "  Variable: CREDITS_API_KEY"
echo "  Value: \$CREDITS_API_KEY"
echo ""
echo "Environment Variables to Set:"
echo "-----------------------------"
echo "# Security"
echo "ADMIN_USERNAME=admin"
echo "ADMIN_PASSWORD=your_secure_password_here"
echo "SECRET_KEY=your_secret_key_here"
echo "CREDITS_API_KEY=your_api_key_here"
echo ""
echo "# Extensions (set in OpenWebUI environment)"
echo "CREDITS_API_PROTOCOL=https"
echo "CREDITS_API_HOST=localhost:8000"
echo "CREDITS_API_SSL_VERIFY=false"
echo "CREDITS_API_KEY=your_api_key_here"
echo ""
echo "⚠️  IMPORTANT: Change default passwords and keys before production!"
echo ""
echo "Run the application to see the actual generated keys."
